- hosts: ubuntu

  tasks:
    - shell: /etc/init.d/apparmor kill
      ignore_errors: True
      
    - shell: invoke-rc.d apparmor stop
      ignore_errors: True
      
    - shell: update-rc.d -f apparmor remove
      ignore_errors: True
      
    - shell: invoke-rc.d apparmor reload
      ignore_errors: True
          
    - lineinfile:
        dest:  /boot/grub/grub.cfg
        state: present
        line: 'apparmor=0'
        ignore_errors: True
        
    - lineinfile:
        dest:  /boot/grub/menul.lst
        state: present
        line: 'apparmor=0'
        ignore_errors: True
