[root@ansible01 ~]# cat ks.yml 
- hosts: titans

  tasks:


    - name: Run the equivalent of "apt-get update" 
      apt:
        update_cache: yes

    - name: mdcluster
      file: path=/cluster state=directory

    - name: mdtmpimage
      file: path=/tmp/image state=directory

    - name: mdclusterapps
      file: path=/cluster/apps state=directory

    - name: mdclusterlogs
      file: path=/cluster/logs state=directory

    - name: mdclusterdata
      file: path=/cluster/data state=directory

    - name: mkdclusterscratch
      file: path=/cluster/scratch state=directory

    - name: mdcacerts
      file: path=/etc/openldap/cacerts/ state=directory



    - name: Installsssd
      apt:
        name: sssd
        state: present
    - name: Installlibpam
      apt:
        name: libpam-sss
        state: present
    - name: Installlibnss
      apt:
        name: libnss-sss
        state: present
    - name: Installautofs
      apt:
        name: autofs
        state: present
    - name: Installtclsh
      apt:
        name: tclsh
        state: present
    - name: Installpydev
      apt:
        name: python-dev
        state: present
    - name: Installpip
      apt:
        name: python-pip
        state: present
    - name: Installpython-virtualenv
      apt:
        name: python-virtualenv
        state: present
    - name: Installlibatlas-base-dev
      apt:
        name: libatlas-base-dev
        state: present
    - name: Installlibatlas-dev
      apt:
        name: libatlas-dev
        state: present
    - name: Installlibatlas3-base
      apt:
        name: libatlas3-base
        state: present
    - name: Installgfortran
      apt:
        name: gfortran
        state: present
    - name: Installlibboost1.55-all-dev
      apt:
        name: libboost1.55-all-dev
        state: present
    - name: Installlibgflags-dev
      apt:
        name: libgflags-dev
        state: present
    - name: Installlibgoogle-glog-dev
      apt:
        name: libgoogle-glog-dev
        state: present
    - name: Installliblmdb-dev
      apt:
        name: liblmdb-dev
        state: present
    - name: Installgit
      apt:
        name: git
        state: present
    - name: Installunzip
      apt:
        name: unzip
        state: present


    - name: Mountiso
      mount:
        name: /tmp/image
        src: santa.bii.a-star.edu.sg:/mnt/image
        fstype: nfs
        opts: rw
        state: mounted

    - copy:
        remote_src: true
        src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/sssd.conf
        dest: /etc/sssd/sssd.conf


    - file:
        src: /bin/bash
        # src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/session
        dest: /usr/local/bin/session
        state: link

    - copy:
        remote_src: true
        src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/hosts
        dest: /etc/hosts

    - copy:
        remote_src: true
        src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/auto.master
        dest: /etc/auto.master

    - copy:
        remote_src: true
        src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/auto.home
        dest: /etc/auto.home

    - service:
        name: autofs
        state: restarted

    - service:
        name: sssd
        state: restarted

