- hosts: 172.20.156.75

  tasks:

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

#BASE="/tmp/image/zkickstartCentos67/scripts-gpu-ubuntu"

# make couple of dirs
    - name: mdcluster
      file: path=/cluster state=directory

    - name: mdtmpimage
      file: path=/tmp/image state=directory

    - name: mdclusterapps
      file: path=/cluster/apps state=directory

    - name: mdclusterlogs
      file: path=/cluster/logs state=directory

    - name: mdclusterdata
      file: path=/cluster/data state=directory

    - name: mkdclusterscratch
      file: path=/cluster/scratch state=directory

    - name: mdcacerts
      file: path=/etc/openldap/cacerts/ state=directory

    - name: mdrootbin
      file: path=/root/bin state=directory

 #mount santa.bii.a-star.edu.sg:/mnt/image /tmp/image

 # do the sssd conf, /usr/local/bin/session

    - name: remove_apparmor
      apt:
        name: apparmor
        state: absent

    - name: Installsssd
      apt:
        name: sssd
        state: present
    - name: Installlibpam
      apt:
        name: libpam-sss
        state: present
    - name: Installlibnss
      apt:
        name: libnss-sss
        state: present
    - name: Installautofs
      apt:
        name: autofs
        state: present
    - name: Installtclsh
      apt:
        name: tclsh
        state: present
    - name: Installpydev
      apt:
        name: python-dev
        state: present
    - name: Installpip
      apt:
        name: python-pip
        state: present
    - name: Installpython-virtualenv
      apt:
        name: python-virtualenv
        state: present
    - name: Installlibatlas-base-dev
      apt:
        name: libatlas-base-dev
        state: present
    - name: Installlibatlas-dev
      apt:
        name: libatlas-dev
        state: present
    - name: Installlibatlas3-base
      apt:
        name: libatlas3-base
        state: present
    - name: Installgfortran
      apt:
        name: gfortran
        state: present
    - name: Installlibboost1.58-all-dev
      apt:
        name: libboost1.58-all-dev
        state: present
    - name: Installlibgflags-dev
      apt:
        name: libgflags-dev
        state: present
    - name: Installlibgoogle-glog-dev
      apt:
        name: libgoogle-glog-dev
        state: present
    - name: Installliblmdb-dev
      apt:
        name: liblmdb-dev
        state: present
    - name: Installgit
      apt:
        name: git
        state: present
    - name: Installunzip
      apt:
        name: unzip
        state: present


#    - name: Mountiso
#      mount:
#        name: /tmp/image
#        src: santa.bii.a-star.edu.sg:/mnt/image
#        fstype: nfs
#        opts: rw
#        state: mounted

    - copy:
        #remote_src: true
        #src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/sssd.conf
        src: /root/santa/sssd.conf
        dest: /etc/sssd/sssd.conf
        mode: 0600

    - file:
        src: /bin/bash
        # src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/session
        dest: /usr/local/bin/session
        state: link

    - file:
        src: /etc/bash.bashrc
        dest: /etc/bashrc
        state: link

    - copy:
        #remote_src: true
        #src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/hosts
        src: /root/santa/hosts
        dest: /etc/hosts

    - copy:
        #remote_src: true
        #src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/auto.master
        src: /root/santa/auto.master
        dest: /etc/auto.master

    - copy:
        #remote_src: true
        #src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/auto.home
        src: /root/santa/auto.home
        dest: /etc/auto.home
    - copy:
        #remote_src: true
        #src: /tmp/image/zkickstartCentos67/scripts-gpu-ubuntu/local.sh
        src: /root/santa/local1604.sh
        dest: /root/bin/local.sh
        mode: 0755

    - lineinfile:
        dest: /etc/rc.local
        state: present
        line: '(/root/bin/local.sh &)'
    
    - service:
        name: autofs
        state: restarted

    - service:
        name: sssd
        state: restarted

    - pip:
        name: --upgrade setuptools
    - pip:
        name: --upgrade pip

    - name: python-matplotlib
      apt:
        name: python-matplotlib
        state: present
    - name: python-sklearn
      apt:
        name: python-sklearn
        state: present
    - name: python-skimage
      apt:
        name: python-skimage
        state: present
    - name: python-h5py
      apt:
        name: python-h5py
        state: present
    - name: python-leveldb
      apt:
        name: python-leveldb
        state: present
    - name: python-networkx
      apt:
        name: python-networkx
        state: present
    - name: python-nose
      apt:
        name: python-nose
        state: present
    - name: python-pandas
      apt:
        name: python-pandas
        state: present
    - name: python-gflags
      apt:
        name: python-gflags
        state: present
    - name: cython
      apt:
        name: cython
        state: present
    - name: ipython
      apt:
        name: ipython
        state: present

    - pip:
        name: easydict

    - name: python-opencv
      apt:
        name: python-opencv
        state: present

    - service:
        name: lightdm
        state: stopped


    - service:
        name: lightdm
        enabled: no
    - service:
        name: cups*
        enabled: no
    - service:
        name: cups.path
        enabled: no
    - service:
        name: cups.service
        enabled: no
    - service:
        name: cups.socket
        enabled: no
    - service:
        name: ModemManager
        enabled: no
